const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const ts=require('typescript');const root=path.resolve(__dirname,'..');const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');const coachingSource=read('src/lib/boardsignal/coaching.ts');
function load(){const compiled=ts.transpileModule(coachingSource,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;const module={exports:{}};vm.runInNewContext(compiled,{module,exports:module.exports,require,console},{filename:'coaching.js'});return module.exports}const m7=load();
const example=(id='g1')=>({id:`${id}:f`,gameId:id,gameUrl:`https://www.chess.com/game/live/${id}`,occurredAt:100,opponent:'Opponent',opponentRating:900,pool:'rapid',moveNumber:12,movePlayed:'Qd2',opponentReply:'Qh4+',summary:'A real supporting event.'});
const candidate=(family='forcing_reply',examples=[example('g1'),example('g2')])=>({key:`m7:2026-08-31:current:${family}`,family,source:'current_week',provenance:'current_period',cueTitle:'Check the reply.',cueCopy:'Scan checks and captures first.',level2Copy:'Put more simply: scan the reply.',periodStart:'2026-08-31',periodEnd:'2026-09-06',evidenceCount:examples.length,gamesConsidered:4,examples});
const state=(overrides={})=>({...m7.stateForNewCandidate(candidate(),'2026-08-31T00:00:00.000Z'),...overrides});
const files={account:read('src/lib/boardsignal/account.ts'),feedback:read('src/lib/boardsignal/server/currentFeedback.ts'),engagement:read('src/lib/boardsignal/server/playerRoomEngagement.ts'),founder:read('src/lib/boardsignal/server/founderEngagement.ts'),ask:read('src/lib/boardsignal/server/m7AskContext.ts'),ui:read('src/components/CurrentBoardSignalEngagement.tsx'),css:read('src/components/CurrentBoardSignalEngagement.module.css')};

test('stable signal identity stays separate from presentation rotation',()=>{const a=candidate('forcing_reply');const b={...a,evidenceCount:4,gamesConsidered:8,examples:[example('g9')]};const s=m7.stateForNewCandidate(a,'2026-08-31T00:00:00Z');const merged=m7.mergeSameSignalState(s,b,'2026-08-31T00:01:00Z');assert.equal(merged.coachingSignalKey,s.coachingSignalKey);assert.equal(merged.cueTitle,s.cueTitle);assert.equal(merged.cueCopy,s.cueCopy)});

test('automatic meaningful returns rotate 1 to 2 to 3 to 1',()=>{let s=state();let a=m7.presentCoachingForSession(s,'session-a',1_000_000);assert.equal(a.state.level,1);let b=m7.presentCoachingForSession(a.state,'session-b',1_100_001);assert.equal(b.state.level,2);let c=m7.presentCoachingForSession(b.state,'session-c',1_200_002);assert.equal(c.state.level,3);let d=m7.presentCoachingForSession(c.state,'session-d',1_300_003);assert.equal(d.state.level,1);assert.equal(d.state.automaticVariantCursor,2)});

test('no-example rotation is 1 to 2 to 1 and never fabricates variant 3',()=>{let s=m7.stateForNewCandidate(candidate('forcing_reply',[]),'2026-08-31T00:00:00Z');let a=m7.presentCoachingForSession(s,'session-a',1_000_000);let b=m7.presentCoachingForSession(a.state,'session-b',1_100_001);let c=m7.presentCoachingForSession(b.state,'session-c',1_200_002);assert.deepEqual([a.state.level,b.state.level,c.state.level],[1,2,1]);assert.deepEqual(Array.from(m7.coachingVariantsForState(c.state)),[1,2])});

test('reload and concurrent tabs do not consume the automatic cursor',()=>{let a=m7.presentCoachingForSession(state(),'session-a',1_000_000);let reload=m7.presentCoachingForSession(a.state,'session-a',1_010_000);assert.equal(reload.state.level,1);assert.equal(reload.state.automaticVariantCursor,2);let tab=m7.presentCoachingForSession(a.state,'session-tab',1_000_500);assert.equal(tab.coalesced,true);assert.equal(tab.state.level,1);assert.equal(tab.state.automaticVariantCursor,2)});

test('manual switching changes only active presentation and leaves auto cursor intact',()=>{let a=m7.presentCoachingForSession(state(),'session-a',1_000_000);assert.equal(a.state.automaticVariantCursor,2);let manual=m7.switchCoachingVariant(a.state,2,'2026-08-31T00:10:00Z');assert.equal(manual.level,2);assert.equal(manual.automaticVariantCursor,2);assert.equal(manual.lastPresentationSource,'MANUAL_SWITCH');let manual2=m7.switchCoachingVariant(manual,3,'2026-08-31T00:11:00Z');assert.equal(manual2.level,3);assert.equal(manual2.automaticVariantCursor,2);let next=m7.presentCoachingForSession(manual2,'session-b',1_100_001);assert.equal(next.state.level,2);assert.equal(next.state.lastPresentationSource,'AUTO_RETURN')});

test('feedback is per-variant, changeable, and never switches presentation',()=>{let s=state();let one=m7.applyCoachingReaction(s,1,'not_helpful','2026-08-31T01:00:00Z').state;assert.equal(one.level,1);assert.equal(one.reactions[1].reaction,'not_helpful');let changed=m7.applyCoachingReaction(one,1,'helpful','2026-08-31T01:01:00Z').state;assert.equal(changed.level,1);assert.equal(changed.reactions[1].reaction,'helpful');let two=m7.applyCoachingReaction({...changed,level:2},2,'helpful','2026-08-31T01:02:00Z').state;assert.equal(two.reactions[1].reaction,'helpful');assert.equal(two.reactions[2].reaction,'helpful');assert.equal(two.level,2)});

test('new signal resets to variant 1 with clean automatic cursor',()=>{const next=m7.stateForNewCandidate(candidate('queen_safety'),'2026-08-31T02:00:00Z');assert.equal(next.level,1);assert.equal(next.automaticVariantCursor,2);assert.equal(Object.keys(next.reactions).length,0);assert.equal(next.presentedSessionIds.length,0)});

test('variant 3 does not create new legacy ladder/progression events',()=>{assert.doesNotMatch(coachingSource,/level3ReachedAt\s*:/);assert.doesNotMatch(coachingSource,/ladderExhaustedAt\s*:/);assert.doesNotMatch(files.feedback,/l1DownToL2|l2DownToL3|level3Down|level3Reached/);assert.doesNotMatch(files.engagement,/recordFounderCoachingProgressionProjection/);assert.doesNotMatch(files.founder,/recordFounderCoachingProgressionProjection|coaching\.l1DownToL2|coaching\.l2DownToL3|coaching\.level3Down|coaching\.level3Reached/)});

test('manual variant switching is distinct from example cycling',()=>{assert.match(files.feedback,/switch_variant/);assert.match(files.feedback,/next_example/);assert.match(files.feedback,/recordFounderCoachingPresentationProjection/);assert.match(files.founder,/AUTO_RETURN/);assert.match(files.founder,/MANUAL_SWITCH/)});

test('player-facing coaching hides numeric level language and keeps reactions changeable',()=>{assert.doesNotMatch(files.ui,/LEVEL 1|LEVEL 2|LEVEL 3|Level 1|Level 2|Level 3|no Level 4|automatic explanation ladder/);assert.match(files.ui,/aria-pressed=\{reaction==="helpful"\}/);assert.match(files.ui,/aria-pressed=\{reaction==="not_helpful"\}/);assert.match(files.ui,/That helped\. BoardSignal saved that\./);assert.match(files.ui,/TRY ANOTHER EXPLANATION/);assert.match(files.css,/button\[aria-pressed="true"\]/)});

test('Ask stays on the stable signal without exposing numeric level language',()=>{assert.match(files.ask,/coachingSignalKey/);assert.match(files.ask,/WHAT SHOULD I ACTUALLY DO/);assert.doesNotMatch(files.ask,/CURRENT COACHING · LEVEL|explanation Level/)});

test('Firestore sanitizer remains recursive and no global ignoreUndefinedProperties is introduced',()=>{const dirty={...state(),family:undefined,examples:[{...example('g1'),opponent:undefined},undefined],presentedSessionIds:['a',undefined,'b']};const safe=m7.firestoreSafeCoachingState(dirty);assert.equal(Object.prototype.hasOwnProperty.call(safe,'family'),false);assert.equal(safe.examples.length,1);assert.equal(safe.presentedSessionIds.length,2);assert.doesNotMatch([coachingSource,files.feedback,files.engagement].join('\n'),/ignoreUndefinedProperties/)});
