"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BOARDSIGNAL_OFFLINE_MAX_SOCIAL_COMPARISONS = exports.BOARDSIGNAL_OFFLINE_MAX_DRAFTS = exports.BOARDSIGNAL_OFFLINE_MAX_DESKS = exports.BOARDSIGNAL_OFFLINE_DB_VERSION = exports.BOARDSIGNAL_OFFLINE_DB_NAME = void 0;
exports.BOARDSIGNAL_OFFLINE_DB_NAME = "boardsignal-offline-v1";
exports.BOARDSIGNAL_OFFLINE_DB_VERSION = 1;
exports.BOARDSIGNAL_OFFLINE_MAX_DESKS = 4;
exports.BOARDSIGNAL_OFFLINE_MAX_DRAFTS = 4;
exports.BOARDSIGNAL_OFFLINE_MAX_SOCIAL_COMPARISONS = 4;
