"use client";
import {usePathname} from "next/navigation";
import type {ReactNode} from "react";
import AdminHeader from "@/components/Header";
import AdminFooter from "@/components/Footer";
import AdminServiceWorker from "@/components/ServiceWorkerRegister";
import AdminInstallPrompt from "@/components/InstallPrompt";
import AdminChatWidget from "@/components/ChatWidget";
import ConnectivityProvider from "@/components/ConnectivityProvider";
import BoardSignalThemeControl from "@/components/BoardSignalThemeControl";
import BoardSignalSituationalMotion from "@/components/BoardSignalSituationalMotion";
import AskBoardSignal from "@/components/AskBoardSignal";
import Link from "next/link";
import SignalMark from "@/components/SignalMark";
import {useEffect,useState} from "react";

function BoardSignalChrome({children}:{children:ReactNode}){const pathname=usePathname();const [theme,setTheme]=useState("light");useEffect(()=>{const sync=()=>setTheme(document.documentElement.dataset.bsTheme||"light");sync();const o=new MutationObserver(sync);o.observe(document.documentElement,{attributes:true,attributeFilter:["data-bs-theme"]});return()=>o.disconnect()},[]);const nav=[["Home","/boardsignal"],["Universe","/feed"],["My BoardSignal","/boardsignal/player-room"]] as const;return <div className="boardsignal-root" data-bs-theme={theme}><ConnectivityProvider><header className="site-header"><a href="#main" className="skip-link">Skip to content</a><div className="container masthead"><Link href="/boardsignal" className="brand-lockup"><SignalMark className="brand-mark"/><span><span className="brand-name">BoardSignal</span><span className="brand-line">Your games, understood</span></span></Link><nav className="desktop-nav" aria-label="BoardSignal navigation">{nav.map(([label,href])=><Link key={href} href={href} className={pathname===href||pathname?.startsWith(href+"/")?"active":""}>{label}</Link>)}</nav><div className="header-actions"><BoardSignalThemeControl className="bs-theme-control-desktop"/><Link href="/boardsignal#get-my-boardsignal" className="button button-dark header-join">Get My BoardSignal</Link></div></div></header><main className="site-main">{children}</main><footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><SignalMark className="footer-mark"/><div><p className="brand-name">BoardSignal</p><p>One seven-day episode at a time.</p></div></div><nav className="footer-links"><Link href="/boardsignal">Home</Link><Link href="/feed">Universe</Link><Link href="/boardsignal/player-room">My Player Room</Link><Link href="/boardsignal/privacy">Privacy</Link></nav><div className="footer-note"><p className="kicker">Privacy rule</p><p>Public highlights. Private improvement guidance.</p></div></div></footer><BoardSignalSituationalMotion/><AskBoardSignal/></ConnectivityProvider></div>;}
export default function AdminHubShell({children}:{children:ReactNode}){const pathname=usePathname();const bs=pathname==="/boardsignal"||pathname?.startsWith("/boardsignal/");const control=pathname?.startsWith("/admin")||pathname==="/login-secret-login-for-admins97F4B2NXQ";if(bs)return <BoardSignalChrome>{children}</BoardSignalChrome>;if(control)return <><div className="admin-route-root">{children}</div><AdminServiceWorker/><AdminInstallPrompt/></>;return <><div className="ah-public-shell"><AdminHeader/><main id="main">{children}</main><AdminFooter/></div><AdminServiceWorker/><AdminInstallPrompt/><AdminChatWidget/></>;}