"use client";
import { useEffect, useState } from "react";
import type { FeaturePipelineItem, PublicFeaturePipelineState } from "@/lib/boardsignal/featurePipeline";

type FounderFeedback = { id: string; itemId?: string; displayName?: string; comment?: string; interested?: boolean; moderationStatus?: string; updatedAt?: string };

type Bundle = { state: PublicFeaturePipelineState; feedback: FounderFeedback[] };
const emptyItem: Partial<FeaturePipelineItem> = { id: "", slug: "", title: "", summary: "", category: "Product", publicQuestion: "", status: "exploring", order: 100, visible: true, releaseNote: "" };

export default function FounderFeaturePipeline() {
  const [bundle, setBundle] = useState<Bundle>(); const [drafts, setDrafts] = useState<Record<string, FeaturePipelineItem>>({}); const [createDraft, setCreateDraft] = useState(emptyItem); const [message, setMessage] = useState("Loading Pipeline…");
  async function load(){const r=await fetch("/api/admin/boardsignal/pipeline",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.error||"Pipeline could not be loaded.");setBundle({state:p.state,feedback:p.feedback||[]});setDrafts(Object.fromEntries((p.state.items as FeaturePipelineItem[]).map((item)=>[item.id,item])));setMessage("");}
  useEffect(()=>{load().catch((e)=>setMessage(e.message));},[]);
  async function post(body:unknown){setMessage("Saving…");const r=await fetch("/api/admin/boardsignal/pipeline",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.error||"Pipeline update failed.");await load();setMessage("Saved.");}
  function field(id:string,key:keyof FeaturePipelineItem,value:unknown){setDrafts((d)=>({...d,[id]:{...d[id],[key]:value}}));}
  if(!bundle)return <section className="admin-card"><p role="status">{message}</p></section>;
  return <div className="admin-stack">
    <section className="admin-card"><div className="admin-card-head"><div><p className="kicker">Public product roadmap</p><h2>Feature Pipeline</h2></div><p role="status">{message}</p></div>
      <div className="admin-grid">{bundle.state.items.sort((a,b)=>a.order-b.order).map((item)=>{const d=drafts[item.id]||item;const itemFeedback=bundle.feedback.filter((f)=>f.itemId===item.id);const pending=itemFeedback.filter((f)=>f.comment&&(!f.moderationStatus||f.moderationStatus==="pending")).length;const approved=itemFeedback.filter((f)=>f.moderationStatus==="approved").length;const hidden=itemFeedback.filter((f)=>f.moderationStatus==="hidden").length;const latest=itemFeedback.map((f)=>f.updatedAt||"").sort().at(-1)||"No input yet";return <article className="admin-card" key={item.id}><p className="kicker">{item.id}</p>
        <label>Title<input value={d.title} onChange={(e)=>field(item.id,"title",e.target.value)} /></label><label>Slug<input value={d.slug} onChange={(e)=>field(item.id,"slug",e.target.value)} /></label><label>Summary<textarea value={d.summary} onChange={(e)=>field(item.id,"summary",e.target.value)} /></label><label>Public question<textarea value={d.publicQuestion||""} onChange={(e)=>field(item.id,"publicQuestion",e.target.value)} /></label><label>Category<input value={d.category} onChange={(e)=>field(item.id,"category",e.target.value)} /></label><label>Status<select value={d.status} onChange={(e)=>field(item.id,"status",e.target.value)}><option value="planned">PLANNED</option><option value="building">BUILDING</option><option value="released">RELEASED</option><option value="exploring">EXPLORING</option></select></label><label>Order<input type="number" value={d.order} onChange={(e)=>field(item.id,"order",Number(e.target.value))} /></label><label>Release note<textarea value={d.releaseNote||""} onChange={(e)=>field(item.id,"releaseNote",e.target.value)} /></label><label><input type="checkbox" checked={d.visible} onChange={(e)=>field(item.id,"visible",e.target.checked)} /> Publicly visible</label>
        <p>{item.interestCount} interested · {item.feedbackCount} feedback identities</p><p>{pending} pending · {approved} approved · {hidden} hidden</p><p>Latest input: {latest}</p><button className="button button-dark" onClick={()=>post({action:"update",id:item.id,item:d}).catch((e)=>setMessage(e.message))}>Save item</button></article>})}</div>
    </section>
    <section className="admin-card"><p className="kicker">Create</p><h2>New Pipeline item</h2><div className="admin-grid"><label>ID<input value={createDraft.id||""} onChange={(e)=>setCreateDraft({...createDraft,id:e.target.value})}/></label><label>Slug<input value={createDraft.slug||""} onChange={(e)=>setCreateDraft({...createDraft,slug:e.target.value})}/></label><label>Title<input value={createDraft.title||""} onChange={(e)=>setCreateDraft({...createDraft,title:e.target.value})}/></label><label>Summary<textarea value={createDraft.summary||""} onChange={(e)=>setCreateDraft({...createDraft,summary:e.target.value})}/></label><label>Category<input value={createDraft.category||""} onChange={(e)=>setCreateDraft({...createDraft,category:e.target.value})}/></label><label>Status<select value={createDraft.status} onChange={(e)=>setCreateDraft({...createDraft,status:e.target.value as FeaturePipelineItem["status"]})}><option value="exploring">EXPLORING</option><option value="planned">PLANNED</option><option value="building">BUILDING</option><option value="released">RELEASED</option></select></label></div><button className="button button-dark" onClick={()=>post({action:"create",item:createDraft}).then(()=>setCreateDraft(emptyItem)).catch((e)=>setMessage(e.message))}>Create item</button></section>
    <section className="admin-card"><p className="kicker">Community signal</p><h2>Moderation</h2>{bundle.feedback.length===0?<p>No Pipeline feedback yet.</p>:<div className="admin-stack">{bundle.feedback.map((f)=><article className="admin-card" key={f.id}><p><strong>{f.displayName||"Anonymous"}</strong> · {f.itemId} · {f.interested?"interested":"not interested"}</p><p>{f.comment||"No written input."}</p><p>Status: {f.moderationStatus||"none"} · {f.updatedAt||""}</p>{f.comment?<div className="admin-actions"><button onClick={()=>post({target:"feedback",action:"approve",feedbackId:f.id}).catch((e)=>setMessage(e.message))}>Approve</button><button onClick={()=>post({target:"feedback",action:"hide",feedbackId:f.id}).catch((e)=>setMessage(e.message))}>Hide</button><button onClick={()=>post({target:"feedback",action:"delete",feedbackId:f.id}).catch((e)=>setMessage(e.message))}>Delete</button></div>:null}</article>)}</div>}</section>
  </div>;
}
