import "server-only";
import { FieldValue } from "firebase-admin/firestore";
import type { BoardSignalAccount, BoardSignalCoachingPresentation, BoardSignalCoachingState } from "@/lib/boardsignal/account";
import type { CurrentEpisodeWithNextGameGuidance } from "@/lib/boardsignal/activeWeekGuidance";
import { coachingCandidateForEpisode, mergeSameSignalState, presentationFromCoachingState, shouldReplaceIncumbentSignal, stateForNewCandidate } from "@/lib/boardsignal/coaching";
import { getAdminDb } from "@/utils/firebaseAdmin";
export function validStoredCoachingState(value:unknown):BoardSignalCoachingState|undefined{if(!value||typeof value!=="object")return undefined;const state=value as Partial<BoardSignalCoachingState>;if(state.schemaVersion!==2)return undefined;if(typeof state.coachingSignalKey!=="string"||!state.coachingSignalKey.startsWith("m7:"))return undefined;if(![1,2,3].includes(Number(state.level)))return undefined;if(typeof state.periodStart!=="string"||typeof state.periodEnd!=="string")return undefined;if(typeof state.cueTitle!=="string"||typeof state.cueCopy!=="string"||typeof state.level2Copy!=="string")return undefined;if(!Array.isArray(state.examples)||!Array.isArray(state.presentedSessionIds))return undefined;return state as BoardSignalCoachingState}
export async function reconcilePlayerCoachingState(uid:string,episode:CurrentEpisodeWithNextGameGuidance):Promise<BoardSignalCoachingPresentation|undefined>{const candidate=coachingCandidateForEpisode(episode);const db=getAdminDb();const ref=db.collection("users").doc(uid);const nowIso=new Date().toISOString();const state=await db.runTransaction(async(transaction:any)=>{const snapshot=await transaction.get(ref);if(!snapshot.exists)return undefined;const account=snapshot.data() as BoardSignalAccount;const existing=validStoredCoachingState(account.coachingState);if(!candidate){if(!existing)return undefined;if(existing.periodStart!==episode.periodStart||existing.family==="loss_run"){transaction.set(ref,{coachingState:FieldValue.delete()},{merge:true});return undefined}const retained={...existing,gamesConsidered:Math.max(existing.gamesConsidered,episode.games),updatedAt:nowIso};transaction.set(ref,{coachingState:retained},{merge:true});return retained}let next:BoardSignalCoachingState;if(!existing||existing.periodStart!==candidate.periodStart)next=stateForNewCandidate(candidate,nowIso);else if(existing.coachingSignalKey===candidate.key)next=mergeSameSignalState(existing,candidate,nowIso);else if(shouldReplaceIncumbentSignal(existing,candidate))next=stateForNewCandidate(candidate,nowIso);else next={...existing,gamesConsidered:Math.max(existing.gamesConsidered,candidate.gamesConsidered),updatedAt:nowIso};transaction.set(ref,{coachingState:next},{merge:true});return next});return state?presentationFromCoachingState(state):undefined}
export function episodeWithCanonicalCoaching(episode:CurrentEpisodeWithNextGameGuidance,coaching:BoardSignalCoachingPresentation|undefined):CurrentEpisodeWithNextGameGuidance{if(!coaching)return episode;const supportingFacts=coaching.provenance==="current_period"?coaching.examples.map((example)=>({...example})):[];const latestMatch=episode.latestGame?.gameId?coaching.examples.find((example)=>example.gameId===episode.latestGame?.gameId):undefined;const guidance={...episode.nextGameGuidance,family:(coaching.family??episode.nextGameGuidance.family) as typeof episode.nextGameGuidance.family,source:coaching.source as typeof episode.nextGameGuidance.source,title:coaching.cueTitle,copy:coaching.cueCopy,evidenceCount:coaching.evidenceCount,gamesConsidered:coaching.gamesConsidered,supportingFacts,reinforcement:coaching.source==="current_week_reinforces_previous_review"&&episode.nextGameGuidance.source==="current_week_reinforces_previous_review"?episode.nextGameGuidance.reinforcement:undefined,reason:undefined,previousReviewPeriod:coaching.previousReviewPeriod??episode.nextGameGuidance.previousReviewPeriod,latestGameNote:episode.latestGame?latestMatch?"Your latest game also contains evidence for the coaching signal BoardSignal is keeping in front of you.":"BoardSignal saw your latest game. The incumbent coaching signal remains the main supported cue for now.":episode.nextGameGuidance.latestGameNote,m7:{coachingSignalKey:coaching.coachingSignalKey,level:coaching.level,provenance:coaching.provenance,cueTitle:coaching.cueTitle,cueCopy:coaching.cueCopy,level2Copy:coaching.level2Copy,evidenceCount:coaching.evidenceCount,gamesConsidered:coaching.gamesConsidered,selectedExample:coaching.selectedExample,ladderExhaustedAt:coaching.ladderExhaustedAt}} as typeof episode.nextGameGuidance & {m7:Record<string,unknown>};const latestGame=episode.latestGame?{...episode.latestGame,supportsSelectedGuidance:Boolean(latestMatch),supportingSummary:latestMatch?.summary}:undefined;return{...episode,nextGameGuidance:guidance,latestGame}}
