import "server-only";
import type { DecodedIdToken } from "firebase-admin/auth";
import type { GuideResponse } from "@/lib/boardsignal/guide";
import { getAdminDb } from "@/utils/firebaseAdmin";
type M7Context={coachingSignalKey:string;level:1|2|3;provenance:"current_period"|"previous_review";cueTitle:string;cueCopy:string;level2Copy?:string;evidenceCount:number;gamesConsidered:number;selectedExample?:{gameId?:string;gameUrl?:string;opponent?:string;opponentRating?:number;pool?:string;moveNumber?:number;movePlayed?:string;opponentReply?:string;summary:string};ladderExhaustedAt?:string};
function normalize(value:unknown){return String(value??"").trim().toLowerCase().replace(/[’]/g,"'").replace(/\s+/g," ")}function validM7(value:unknown):M7Context|undefined{if(!value||typeof value!=="object")return undefined;const item=value as Partial<M7Context>;if(typeof item.coachingSignalKey!=="string"||!item.coachingSignalKey.startsWith("m7:"))return undefined;if(item.level!==1&&item.level!==2&&item.level!==3)return undefined;if(item.provenance!=="current_period"&&item.provenance!=="previous_review")return undefined;if(typeof item.cueTitle!=="string"||typeof item.cueCopy!=="string")return undefined;return item as M7Context}
async function loadM7(token:DecodedIdToken){const session=await getAdminDb().collection("users").doc(token.uid).collection("guide").doc("session").get();const currentEpisode=session.data()?.currentEpisode as {nextGameGuidance?:{m7?:unknown}}|undefined;return validM7(currentEpisode?.nextGameGuidance?.m7)}
function response(context:M7Context,reply:string,chips:string[]):GuideResponse{return{reply,chips:chips.slice(0,4),actions:[],handoffAvailable:false,intent:"explain_signal",category:"signal_explanation",provenance:{kind:"desk",id:`coaching:${context.coachingSignalKey}:level${context.level}`,title:`CURRENT COACHING · LEVEL ${context.level}`}}}
function exampleLine(context:M7Context){const example=context.selectedExample;if(!example?.summary)return"BoardSignal does not have a real stored same-signal game example for this coaching state, so I won't invent one.";const meta=[example.opponent?`vs ${example.opponent}${example.opponentRating?` (${example.opponentRating})`:""}`:undefined,example.pool,example.moveNumber?`move ${example.moveNumber}`:undefined].filter(Boolean).join(" · ");const moves=example.movePlayed?` You played ${example.movePlayed}${example.opponentReply?` and the reply was ${example.opponentReply}`:""}.`:"";return`${meta?`${meta}: `:""}${example.summary}.${moves}`.replace("..",".")}
export async function m7CoachingAskResponse(input:{token?:DecodedIdToken;message?:unknown;pathname?:unknown;activeTab?:unknown}):Promise<GuideResponse|undefined>{if(!input.token||!String(input.pathname??"").includes("boardsignal/player-room"))return undefined;if(input.activeTab&&String(input.activeTab)!=="desk")return undefined;const message=normalize(input.message);if(!/what should i actually do|about this coaching signal|show me another example|what happened in this game|why is this still the main thing|why this coaching|explain this coaching/.test(message))return undefined;const context=await loadM7(input.token);if(!context)return undefined;const chips=["WHY?","WHAT SHOULD I ACTUALLY DO?",...(context.selectedExample?["WHAT HAPPENED IN THIS GAME?"]:[]),"SHOW ME ANOTHER EXAMPLE"];if(/what happened in this game|show me another example/.test(message))return response(context,exampleLine(context),chips);if(/what should i actually do|about this coaching signal/.test(message))return response(context,`Keep the same cue: ${context.cueCopy} BoardSignal is on explanation Level ${context.level}; the underlying coaching signal has not changed.`,chips);const source=context.provenance==="previous_review"?"This cue still comes from your last completed Review because the current period has not supplied enough supported evidence to replace it.":`This is current-period evidence: ${context.evidenceCount} supporting game${context.evidenceCount===1?"":"s"} out of ${context.gamesConsidered} checked.`;return response(context,`${context.cueTitle} ${source}${context.level>=2&&context.level2Copy?` Another way to think about it: ${context.level2Copy}`:""}`,chips)}
